"""addition of phone number

Revision ID: 563fe6c18221
Revises: 5e8c3cca6d1d
Create Date: 2022-07-12 21:22:25.685786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563fe6c18221'
down_revision = '5e8c3cca6d1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
